version: '3.8'

services:
  development:
    environment:
      - CLI_TOKEN=${CLI_TOKEN}
      - authors=${authors}
      - repositories=${repositories}
      - days=${days}
    build: .
    command: /scripts/main.sh
    
