name: PRS Checker | PRs waiting to long for review

on:
  workflow_call:
    inputs:
      authors:
        description: 'Authors of the PRs'
        required: true
        default: 'piotrlatala ArekEvo aleksander-pisarek PiotrPieprzyk'
      repositories:
        description: 'Repositories to check'
        required: true
        default: 'EENCloud/WEB-VMS-WebApp EENCloud/frontend-gui EENCloud/WEB-EEWC-Components EENCloud/WEB-Floor-Plan'
      days:
        description: 'Days to wait for review'
        required: true
        default: '2'
    secrets:
      - CLI_TOKEN:
          description: 'Github token. Read README.md for more information'
          required: true

jobs:
  prs-waiting-to-long-for-review:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts/prs-waiting-to-long-for-review
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # Build the Docker image
      - name: Build with docker compose
        run: docker compose build
      
      # Run the container
      - name: Run with docker compose
        env:
          CLI_TOKEN: ${{ secrets.CLI_TOKEN }}
          authors: ${{ inputs.authors }}
          repositories: ${{ inputs.repositories }}
          days: ${{ inputs.days }}
        run: docker compose run development
