name: Docker Compose Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker-compose-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts/prs-waiting-to-long-for-review
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # Set the test environment variable
      - name: Set test environment variable
        run: echo "test=test_value" >> $GITHUB_ENV
      
      # Build the Docker image
      - name: Build with docker compose
        run: docker compose build
      
      # Run the service
      - name: Run with docker compose
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          test: ${{ env.test }}
        run: docker compose run development
