name: PRS Checker | PRs waiting to long for review

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  prs-waiting-to-long-for-review:
    uses: ./.github/workflows/prs-waiting-to-long-for-review-reusable.yml
    secrets:
      CLI_TOKEN: ${{ secrets.CLI_TOKEN }}
    with:
      authors: 'piotrlatala ArekEvo aleksander-pisarek PiotrPieprzyk'
      repositories: 'EENCloud/WEB-VMS-WebApp EENCloud/frontend-gui EENCloud/WEB-EEWC-Components EENCloud/WEB-Floor-Plan'
      days: '2'
