name: Docker Compose Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker-compose-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts/prs-waiting-to-long-for-review
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # Build the Docker image
      - name: Build with docker compose
        run: docker compose build
      
      # Run the container
      - name: Run with docker compose
        env:
          CLI_TOKEN: ${{ secrets.CLI_TOKEN }}
        run: docker compose run development
